config/routes.rb
Rails.application.routes.draw do
  devise_for :models
	root 'welcome#home'
	# get 'home', to: 'welcome#home'
	get 'about', to: 'welcome#about'
	resources :items
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ActiveRecord::Base
	validates :name, presence: true, length: {minimum: 3, maxiumum: 50}
	validates :sku, presence: true, length: {minimum: 10, maxiumum: 10}
	validates :active, presence: true
end 

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base

end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	before_action :set_item, only: [:edit, :update, :show, :destroy]
	
	def index
		@items = Item.all
	end 

	def new
		@item = Item.new
	end

	def edit
	end

	def create
		#render plain: params[:item].inspect
		@item = Item.new(item_params)
		if @item.save
			flash[:notice] = "Item was successfully created"
			redirect_to item_path(@item)
		else 
			render 'new'
		end
	end

	def update
		if @item.update(item_params)
			flash[:notice] = "item was updated"
			redirect_to item_path(@item)
		else
			render 'edit'
		end
	end

	def show
	end

	def destroy
		@item.destroy
		flash[:notice] = "Item was deleted"
		redirect_to items_path
	end

	private
		def set_item
			@item = Item.find(params[:id])
		end 

		def item_params
			params.require(:item).permit(:name, :sku, :id, :active)
		end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def home
		
	end

	def about
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/_form.html.erb
<% if @item.errors.any? %>
<ul>
	<% @item.errors.full_messages.each do |msg| %>
	<li><%= msg %></li>
	<% end %>
</ul>
<% end %>
<%= form_for @item do |f| %>
	<p>
		<%= f.label :name %>
		<%= f.text_field :name %><br/>
	</p>
	<p>
		<%= f.label :sku %>
		<%= f.text_area :sku %><br/>
	</p>
	<p>
		<%= f.label :active %>
		<%= f.text_field :active %><br/>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end -%>



<%= link_to 'back to item listing', items_path %>

app/views/items/edit.html.erb
<h1>Editing existing item</h1>
<%= render 'form' %>

app/views/items/index.html.erb
<h1>Listing all items</h1>
<p>
	<%= link_to "Create new item", new_item_path %>
</p>


<table>
	<tr>
		<th>ID</th>
		<th>Name</th>
		<th>SKU</th>
		<th>Active</th>
	</tr>
	<% @items.each do |item| %>
	<tr>
		<td><%= item.id %></td>
		<td><%= item.name %></td>
		<td><%= item.sku %></td>
		<td><%= item.active %></td>
		<td><%= link_to 'Edit', edit_item_path(item) %></td>
		<td><%= link_to 'Show', item_path(item) %></td>
		<td><%= link_to 'Delete', item_path(item), method: :delete, data: {confirm:"are you sure?"} %></td>
	</tr>
	<% end %>
</table>

app/views/items/new.html.erb
<h1> Create a new item</h1>
<%= render 'form' %>

app/views/items/show.html.erb
<h1>Showing item</h1>

<p>
	name: <%= @item.name %>
</p>

<p>
	sku: <%= @item.sku %>
</p>

<p>
	active: <%= @item.active %>
</p>

<p>
	created_at: <%= @item.created_at %>
</p>

<p>
	updated_at: <%= @item.updated_at %>
</p>

<%= link_to 'edit to this item', edit_item_path(@item) %> |

<%= link_to 'back to item listing', items_path %>

app/views/layouts/_footer.html.erb
<div>
	<footer class="footer">
		<small>
			Copyright cw
		</small>
		<nav>
			<ul>
				<li>
					<%= link_to "About", about_path %>
				</li>
			</ul>
		</nav>
	</footer>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
	<ul>
		<li><%= msg %></li>
	</ul>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "Item Mgmt", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li>
        <%= link_to "Items", items_path %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="Action" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <li><%= link_to "New Item", new_item_path %></li>
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Neptune</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
  	<%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/welcome/about.html.erb
<h1>About</h1>

<%= link_to "Home", root_path %>

app/views/welcome/home.html.erb
<div class="center jumbotron">
  <h1>Neptune</h1>
  <p>Welcome to item mgmt UI</p>
  <%= link_to "Sign up now", "#", class: "btn btn-primary mb1 white btn-sliver btn-lg btn-xlarge" %>
</div>


<%= link_to "Item Listing", items_path%>|<%= link_to "About", about_path %>